export const GET_EXIT_CLASS='getExitClass'
export const GET_SELECT_STUDENTS='getSelectStudents'
export const GET_SELECT_COMPANY='getSelectCompany'
export const DEFAULT_PAGE_SIZE='5'
export const GET_SELECTED_CLASS='getSelectedClass'
export const GET_CHANGE_COMPANY='getChangeCompany'
// export const GET_CHANGE_COMPANY_TYPE='getChangeCompanyType'
